spring:

  application:
    name: stock-one

  datasource:
    url: jdbc:postgresql://localhost:5432/stockone-db
    username: admin
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

